# Generated by Django 3.1 on 2021-02-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LanOz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oz', models.TextField()),
                ('uz', models.TextField()),
                ('ru', models.TextField()),
                ('key', models.CharField(max_length=100)),
            ],
        ),
    ]
