# Generated by Django 3.1 on 2021-02-16 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botconfig', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LanOz',
            new_name='Lan',
        ),
    ]
