# Generated by Django 3.1 on 2021-03-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botconfig', '0008_category_podcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='lan',
            field=models.CharField(choices=[('oz', "O'zbek"), ('uz', 'Узбек'), ('ru', 'Руский')], default='uz', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podcategory',
            name='lan',
            field=models.CharField(choices=[('oz', "O'zbek"), ('uz', 'Узбек'), ('ru', 'Руский')], default='uz', max_length=30),
            preserve_default=False,
        ),
    ]
