# Generated by Django 3.1 on 2021-03-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botconfig', '0009_auto_20210303_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avto',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
