# Generated by Django 3.1 on 2021-03-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botconfig', '0010_auto_20210304_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='oz',
        ),
        migrations.RenameField(
            model_name='podcategory',
            old_name='name',
            new_name='oz',
        ),
        migrations.RemoveField(
            model_name='category',
            name='lan',
        ),
        migrations.RemoveField(
            model_name='podcategory',
            name='lan',
        ),
        migrations.AddField(
            model_name='category',
            name='ru',
            field=models.CharField(default='sfsdf', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='uz',
            field=models.CharField(default='sdfsdf', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podcategory',
            name='ru',
            field=models.CharField(default='sdfsdf', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podcategory',
            name='uz',
            field=models.CharField(default='sdfsdf', max_length=80),
            preserve_default=False,
        ),
    ]
