# Generated by Django 3.1 on 2021-03-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botconfig', '0013_tuman_viloyat'),
    ]

    operations = [
        migrations.AddField(
            model_name='viloyat',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
