# Generated by Django 3.1 on 2021-03-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botconfig', '0015_startnarx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startnarx',
            name='narx',
            field=models.CharField(max_length=50),
        ),
    ]
