# Generated by Django 3.1 on 2021-03-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botconfig', '0016_auto_20210314_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('day', models.IntegerField(default=0)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
