# Generated by Django 3.1 on 2021-03-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botconfig', '0017_paket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paket',
            old_name='name',
            new_name='name_oz',
        ),
        migrations.AddField(
            model_name='paket',
            name='name_ru',
            field=models.CharField(default='asd', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paket',
            name='name_uz',
            field=models.CharField(default='asdasd', max_length=50),
            preserve_default=False,
        ),
    ]
