# Generated by Django 3.1 on 2021-03-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botconfig', '0020_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='error_message',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='messages',
            name='success_message',
            field=models.IntegerField(default=0),
        ),
    ]
