# Generated by Django 3.1 on 2021-03-24 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botconfig', '0021_auto_20210324_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='success_message',
        ),
    ]
