# Generated by Django 3.1 on 2021-03-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botconfig', '0022_auto_20210324_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='video',
        ),
        migrations.AddField(
            model_name='config',
            name='list_count',
            field=models.IntegerField(default=5, verbose_name="E'lonlar ro'yxat soni"),
        ),
    ]
