# Generated by Django 3.1 on 2021-03-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botconfig', '0023_auto_20210329_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paket',
            name='price',
            field=models.IntegerField(max_length=80, unique=True, verbose_name='Narxi (sum)'),
        ),
    ]
