# Generated by Django 3.1 on 2021-04-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botconfig', '0024_auto_20210331_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paket',
            name='price',
            field=models.IntegerField(verbose_name='Narxi (sum)'),
        ),
    ]
