# Generated by Django 3.1 on 2021-04-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botconfig', '0025_auto_20210402_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='oz',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True, verbose_name="O'zbek"),
        ),
        migrations.AlterField(
            model_name='category',
            name='ru',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True, verbose_name='Rus'),
        ),
        migrations.AlterField(
            model_name='category',
            name='uz',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True, verbose_name='Krill'),
        ),
        migrations.AlterField(
            model_name='podcategory',
            name='oz',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True, verbose_name="O'zbek"),
        ),
        migrations.AlterField(
            model_name='podcategory',
            name='ru',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True, verbose_name='Rus'),
        ),
        migrations.AlterField(
            model_name='podcategory',
            name='uz',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True, verbose_name='Krill'),
        ),
    ]
