# Generated by Django 3.1 on 2021-03-06 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botconfig', '0010_auto_20210304_0008'),
        ('bot', '0002_tguser_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kub', models.CharField(max_length=30)),
                ('telefon', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('avto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botconfig.avto')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botconfig.category')),
                ('podcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botconfig.podcategory')),
                ('tuman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botconfig.tuman')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.tguser')),
                ('viloyat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botconfig.viloyat')),
            ],
        ),
    ]
