# Generated by Django 3.1 on 2021-03-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botconfig', '0014_viloyat_status'),
        ('bot', '0003_auto_20210306_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='kub',
        ),
        migrations.AddField(
            model_name='usercart',
            name='kub',
            field=models.ManyToManyField(to='botconfig.AvtoKub'),
        ),
        migrations.RemoveField(
            model_name='usercart',
            name='tuman',
        ),
        migrations.AddField(
            model_name='usercart',
            name='tuman',
            field=models.ManyToManyField(to='botconfig.Tuman'),
        ),
    ]
