# Generated by Django 3.1 on 2021-03-08 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botconfig', '0014_viloyat_status'),
        ('bot', '0004_auto_20210308_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='avto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='botconfig.avto'),
        ),
    ]
