# Generated by Django 3.1 on 2021-03-10 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botconfig', '0014_viloyat_status'),
        ('bot', '0007_auto_20210310_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='avto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='botconfig.avto'),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='kub',
            field=models.ManyToManyField(null=True, to='botconfig.AvtoKub'),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='podcategory',
            field=models.ManyToManyField(null=True, to='botconfig.PodCategory'),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='telefon',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='tuman',
            field=models.ManyToManyField(null=True, to='botconfig.Tuman'),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='viloyat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='botconfig.viloyat'),
        ),
    ]
