# Generated by Django 3.1 on 2021-03-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botconfig', '0014_viloyat_status'),
        ('bot', '0008_auto_20210311_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='viloyat',
        ),
        migrations.AddField(
            model_name='usercart',
            name='viloyat',
            field=models.ManyToManyField(null=True, to='botconfig.Viloyat'),
        ),
    ]
