# Generated by Django 3.1 on 2021-03-14 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botconfig', '0015_startnarx'),
        ('bot', '0009_auto_20210312_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='narx',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='botconfig.startnarx'),
        ),
    ]
