# Generated by Django 3.1 on 2021-03-15 09:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botconfig', '0017_paket'),
        ('bot', '0010_usercart_narx'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 14, 29, 10, 720705)),
        ),
        migrations.AddField(
            model_name='usercart',
            name='deatline',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 30, 14, 29, 10, 720705)),
        ),
        migrations.AddField(
            model_name='usercart',
            name='paket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='botconfig.paket'),
        ),
    ]
