# Generated by Django 3.1 on 2021-03-21 17:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_auto_20210321_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='status_check',
            field=models.BooleanField(default=False, verbose_name="To'liq emas e'lon"),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='deatline',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 22, 17, 36, 45, 41730, tzinfo=utc), verbose_name='Amal qilish vaqti'),
        ),
    ]
