# Generated by Django 3.1 on 2021-03-26 11:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('botconfig', '0022_auto_20210324_2306'),
        ('bot', '0017_auto_20210324_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='deatline',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 11, 48, 23, 679329, tzinfo=utc), verbose_name='Amal qilish vaqti'),
        ),
        migrations.RemoveField(
            model_name='usercart',
            name='kub',
        ),
        migrations.AddField(
            model_name='usercart',
            name='kub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='botconfig.avtokub', verbose_name="Avtomobil sig'imi"),
        ),
        migrations.RemoveField(
            model_name='usercart',
            name='podcategory',
        ),
        migrations.AddField(
            model_name='usercart',
            name='podcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='botconfig.podcategory', verbose_name='Podkategoryalar'),
        ),
        migrations.RemoveField(
            model_name='usercart',
            name='tuman',
        ),
        migrations.AddField(
            model_name='usercart',
            name='tuman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='botconfig.tuman', verbose_name='Tumanlar'),
        ),
        migrations.RemoveField(
            model_name='usercart',
            name='viloyat',
        ),
        migrations.AddField(
            model_name='usercart',
            name='viloyat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='botconfig.viloyat', verbose_name='Viloyatlar'),
        ),
    ]
