# Generated by Django 3.1 on 2021-03-30 19:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0021_auto_20210329_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='deatline',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 31, 19, 56, 6, 378213, tzinfo=utc), verbose_name='Amal qilish vaqti'),
        ),
    ]
