# Generated by Django 3.1 on 2021-04-02 11:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('botconfig', '0025_auto_20210402_1611'),
        ('bot', '0022_auto_20210331_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='avto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='botconfig.avto', verbose_name='Avtomobil'),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='deatline',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 3, 11, 11, 8, 78558, tzinfo=utc), verbose_name='Amal qilish vaqti'),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='kub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='botconfig.avtokub', verbose_name="Avtomobil sig'imi"),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='paket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='botconfig.paket', verbose_name='Tarif'),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='podcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='botconfig.podcategory', verbose_name='Podkategoryalar'),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='telefon',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='tuman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='botconfig.tuman', verbose_name='Tumanlar'),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram username'),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='viloyat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='botconfig.viloyat', verbose_name='Viloyatlar'),
        ),
    ]
