# Generated by Django 3.1 on 2021-04-02 11:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('botconfig', '0026_auto_20210402_1613'),
        ('bot', '0023_auto_20210402_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='deatline',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 3, 11, 13, 42, 881274, tzinfo=utc), verbose_name='Amal qilish vaqti'),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='narx',
            field=models.ForeignKey(blank=True, help_text='--------- belgi kelishilgan narx', null=True, on_delete=django.db.models.deletion.CASCADE, to='botconfig.startnarx', verbose_name="Boshlang'ich narx"),
        ),
    ]
