# Generated by Django 3.1 on 2021-04-04 08:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0024_auto_20210402_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=50, null=True)),
                ('narx', models.CharField(max_length=50, null=True)),
                ('podcategory', models.CharField(max_length=50, null=True)),
                ('avto', models.CharField(max_length=50, null=True)),
                ('avtokub', models.CharField(max_length=50, null=True)),
                ('viloyat', models.CharField(max_length=50, null=True)),
                ('tuman', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='usercart',
            name='deatline',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 5, 8, 59, 38, 268451, tzinfo=utc), verbose_name='Amal qilish vaqti'),
        ),
    ]
