# Generated by Django 3.1 on 2021-04-06 05:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0025_auto_20210404_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersearch',
            name='narx',
        ),
        migrations.RemoveField(
            model_name='usersearch',
            name='status',
        ),
        migrations.AlterField(
            model_name='usercart',
            name='deatline',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 5, 13, 28, 474594, tzinfo=utc), verbose_name='Amal qilish vaqti'),
        ),
    ]
