# Generated by Django 3.1 on 2021-04-15 20:33

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0026_auto_20210406_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='date_sort',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='TEGILMASIN!!!'),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='deatline',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 16, 20, 33, 40, 419736, tzinfo=utc), verbose_name='Amal qilish vaqti'),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='status_check',
            field=models.BooleanField(default=False, verbose_name="To'liq emas e'lon (BUNGA TEGILMASIN!)"),
        ),
    ]
