# Generated by Django 3.1 on 2021-04-15 20:35

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0027_auto_20210416_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='date_sort',
            field=models.DateTimeField(default=django.utils.timezone.now, unique=True, verbose_name='TEGILMASIN!!!'),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='deatline',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 16, 20, 35, 9, 520163, tzinfo=utc), verbose_name='Amal qilish vaqti'),
        ),
    ]
