# Generated by Django 3.1 on 2021-04-15 20:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0029_auto_20210416_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='deatline',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 16, 20, 35, 58, 200045, tzinfo=utc), verbose_name='Amal qilish vaqti'),
        ),
    ]
